encoder: 
	g++ --std=c++11 -O2 -o out/encoder encoder.cpp `Magick++-config --cppflags --cxxflags --ldflags --libs`

decoder: 
	g++ --std=c++11 -O2 -o out/decoder decoder.cpp `Magick++-config --cppflags --cxxflags --ldflags --libs`

all: encoder decoder